# Generated by Django 4.1.5 on 2023-08-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('year', models.IntegerField()),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
